### ISSUE TITLE
大佬能不能更新一下啊，

### ISSUE THREAD

**Issue by mendax1234** [ialoe/hexo-themes-matery-pro#1]
看了大佬最新的博客，能不能更新一下这个库呢。
还有一个问题就是如果我用的是官方的matery，我改怎么加暗黑模式？

**Comment by aloeJun** [comment]
这两天会在博客更新暗黑模式的教程，需要什么功能可以留言

**Comment by mendax1234** [comment]
大佬能否研究下如何才能自动隐藏掉最上面的导航栏，感觉一直在那里固定者浪费空间

从 Windows 版邮件发送

发件人: 闲花手札
发送时间: 2021年8月11日 9:26
收件人: ialoe/hexo-themes-islu
抄送: mendax1234; Author
主题: Re: [ialoe/hexo-themes-islu] 大佬能不能更新一下啊， (#1)

这两天会在博客更新暗黑模式的教程，需要什么功能可以留言

**Comment by aloeJun** [comment]
是那种向上滑动滚动条时会出现，向下滑动时会消失的么

**Comment by aloeJun** [comment]
暗黑模式已更新

**Comment by mendax1234** [comment]
是的

发自我的iPhone

**Comment by aloeJun** [comment]
看一下是我现在博客的这种么，是的话下午就出一个教程

**Comment by mendax1234** [comment]
是滴是滴，大佬太巨了.还有就是大佬那个目录是怎么弄的，能否也更新一下.


发自我的iPhone

**Comment by mendax1234** [comment]
大佬更新好了吗

**Comment by mendax1234** [comment]
大佬，按照你的方式加了暗黑模式，但是加粗后的字还是不清楚。

![](https://pic.imgdb.cn/item/6113cbb65132923bf804cf42.jpg)

**Comment by ialoe** [comment]
细节修改我下面写了如何修改，你看着改一下或者你加一下我QQ180353980,我帮你改一下细节

**Comment by mendax1234** [comment]
我加了如下代码到dark.css,但还是没有效果
```
/*给暗黑模式下的.test添加字体颜色变红样式*/
body.dark .test{
    color: red !important;
}
```
还有就是那个目录按钮的位置好像改不了，我改了如下代码，还是不行
```
#floating-toc-btn {
    position: fixed;
    right: 15px;
    bottom: 50px;
    padding-top: 15px;
    margin-bottom: 0;
    z-index: 998;
}

```

**Comment by aloeJun** [comment]
你把网址发一下，我看一下

**Comment by mendax1234** [comment]
https://www.6940violetz.top/2021/08/10/di-yi-jie-frc-ji-zhu-jiao-liu-hui/

**Comment by aloeJun** [comment]
![image](https://user-images.githubusercontent.com/69854983/129152540-0d94774f-c3fb-4311-9082-7c358c98722a.png)
![image](https://user-images.githubusercontent.com/69854983/129152664-62410edc-6a70-4765-ad41-cda7320de40a.png)
这个能看懂么，再试一下

**Comment by mendax1234** [comment]
是在dark.css里面加吗，加了还是没用啊

**Comment by mendax1234** [comment]
可以了，但是下面那个转载申明还是不行

**Comment by mendax1234** [comment]
还有就是文章的目录过长的话，拉到最底下有bug，它会陷进去。

![](https://pic.imgdb.cn/item/6114cda55132923bf89ed56a.jpg)

**Comment by mendax1234** [comment]
![](https://pic.imgdb.cn/item/6114cda55132923bf89ed56a.jpg)

**Comment by aloeJun** [comment]
![image](https://user-images.githubusercontent.com/69854983/129156214-8d67aa5c-5d5d-4bda-ade3-9a4615f5754d.png)
活学活用啊，暗黑模式原理是用的CSS选择器中的后代选择器

**Comment by aloeJun** [comment]
![image](https://user-images.githubusercontent.com/69854983/129156453-18d6cb21-f5db-44e6-9502-2ad9500672ec.png)
我这里mei'you'd没有的你的目录问题，但是可以通过修改footer的CSS(z-index)调节上下层级

**Comment by mendax1234** [comment]
![](https://pic.imgdb.cn/item/6114d1285132923bf8a6033d.jpg)

还有就是这个目录怎么跳到下面空的位置

**Comment by aloeJun** [comment]
没有理解你什么意思，如果过长的话会自动向下扩展，默认是向上对齐

**Comment by mendax1234** [comment]
是这个目录的按钮

**Comment by mendax1234** [comment]
他的位置太上面了，想把他弄下来

**Comment by aloeJun** [comment]
在my.css里我写的有注释，/* 目录按钮样式修改 */
#floating-toc-btn 可以修改bottom的像素值调整上下位置

**Comment by mendax1234** [comment]
好的，谢谢，我之前在post-detail-toc.css里改，没有用了。顺便问一下在图片里嵌入链接，matery好像不支持是吗，就是在图片的链接外再套一层链接，然后点击图片就能跳到对应的网站而不是打开图片

**Comment by mendax1234** [comment]
我改了，但好像还是没有效果

**Comment by aloeJun** [comment]
那个可以自己添加，修改my.css中的，我写注释了

**Comment by mendax1234** [comment]
那个我感觉我的mycss没有生效，不知道为什么，按钮的位置改了之后还是没有变化

**Comment by mendax1234** [comment]
大佬，这个cdn加速只能备案才能用吗，我githubpage的服务器不是在美国吗，请问大佬如何解决的。

**Comment by aloeJun** [comment]
加我联系方式，这里不是聊天的地方

**Comment by mendax1234** [comment]
emmm,要不开个gitter？

**Comment by mendax1234** [comment]
不太方便加

**Comment by mendax1234** [comment]
大佬，请问暗黑模式怎么自动更改网站内命令行的颜色呢
