### ISSUE TITLE
关于Pjax实现全局音乐播放能否出个教程？

### ISSUE THREAD

**Issue by Halecoder** [ialoe/hexo-themes-matery-pro#11]

**Comment by Halecoder** [comment]
网上的都是关于Next主题的，谢谢

**Comment by Halecoder** [comment]
好像是这个原因：使用pjax托管页面后产生了一些问题，因为页面不刷新，所以切换页面后有一些原来会执行的javascript代码不会再执行，另外一些监听事件也出了问题，解决方法也比较容易，把这些事件纳入pjax管理，在pjax执行完后添加相应的回调函数即可。

我添加了一个加载动画，所以失效了

**Comment by aloeJun** [comment]
我在博客写了一篇文章是关于给matery适配pjax的，就是为了便于那些已经魔改很多的，不方便重新修改的人适配的

**Comment by aloeJun** [comment]
可以来尝试一下新的，简化很多代码，暂时没有尝试功能有无失效
